kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: search
  labels:
    app: search
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: openjdk:8-jre-alpine
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1024Mi"
          requests:
            memory: "256Mi"
        ports:
        - containerPort: 8085
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://10.1.20.15:7070/eureka/"
        volumeMounts:
        - name: log-config
          mountPath: /data/logs
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: log-config
        hostPath:
          path: /var/log/containers/
      - name: tz-config
        hostPath: 
          path: /etc/localtime