server:
  port: 8182
spring:
  application:
    name: training
  profiles:
    active: base
  datasource:
    url: jdbc:mysql://${host}:3306/training_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    service-url:
      defaultZone: http://${host}:8889/eureka
  instance:
    prefer-ip-address: true
    ip-address: ${host}