host: 192.168.94.241
server:
  port: 8888
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://${host}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false